export const options1 = [
  { value: "kimchi", label: "Kimchi" },
  { value: "lagman", label: "Lagman" },
  { value: "kimpab", label: "Kimpab" },
  { value: "sushi", label: "Sushi" },
  { value: "jajangmyeon", label: "Jajangmyeon" },
];
export const options2 = [
  { value: "payPal", label: "PayPal" },
  { value: "visa", label: "Visa" },
  { value: "elcard", label: "Elcard" },
  { value: "kaspi", label: "Kaspi" },
];

const fod = [
  {
    id: "1",
    img: "https://i.yapx.ru/VUv6X.png",
    title: "Jajangmyeon",
    price: "25.99",
    reviews: "100",
    composition: [
      "Sugar",
      "Strawberry jam",
      "Rice win vinegar",
      "Soy sauce",
      "Garlic",
      "Ginger",
      "Butter",
    ],
  },
  {
    id: "2",
    img: "https://i.yapx.ru/VUv7w.png",
    title: "Gimbap",
    price: "10.99",
    reviews: "150",
    composition: ["Ketchup", "Strawberry jam", "Soy sauce", "Garlic", "Butter"],
  },
  {
    id: "3",
    img: "https://i.yapx.ru/VUv7k.png",
    title: "Kimchi",
    price: "211.99",
    reviews: "123",
    composition: ["Meat", "Strawberry jam", "Garlic", "Butter"],
  },
  {
    id: "4",
    img: "https://i.yapx.ru/VUv7Q.png",
    title: "Kimchi Jjigae",
    price: "210.99",
    reviews: "320",
    composition: [
      "Chicken",
      "Spicy sous",
      "Strawberry jam",
      "Garlic",
      "Butter",
    ],
  },
  {
    id: "5",
    img: "https://i.yapx.cc/VUv2N.png",
    title: "Yangnyeom Chicken",
    price: "50.99",
    reviews: "214",
    composition: ["Ice Cream", "Cheaps", "Strawberry jam", "Garlic", "Butter"],
  },
  {
    id: "6",
    img: "https://i.yapx.ru/VUv8V.png",
    title: "Beef Noodle Soup",
    price: "4.99",
    reviews: "512",
    composition: [
      "Butter",
      "Potato",
      "Tomato",
      "Mayones",
      "Strawberry jam",
      "Garlic",
    ],
  },
];
